name: CI - Midnight.js
env:
  MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: string
      should_prerelease:
        required: true
        type: string

permissions:
  contents: read
  issues: read
  id-token: write
  packages: write
  checks: write
  pull-requests: write

concurrency:
  group: MN-JS-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: inputs.should_run == 'true'
    uses: ./.github/workflows/ci-base.yml
    with:
      yarn_filter: --filter="./packages/*"
      yarn_lint_paths: ./packages
    secrets: inherit

  cd-prerelease:
    runs-on: ubuntu-latest
    needs: ci
    if: inputs.should_prerelease == 'true'
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # ratchet:actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install direnv
        run: curl -sfL https://direnv.net/install.sh | bash

      - name: Load environment from .envrc
        run: |
          direnv allow .
          direnv export gha >> "$GITHUB_ENV"

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # ratchet:actions/setup-node@v4
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@midnight-ntwrk'
          node-version-file: '.nvmrc'
          cache: 'yarn'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Configure yarn
        run: yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Cache Turbo and Yarn dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            **/node_modules
            ~/.yarn
            .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/turbo.json') }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Temp bump prerelease
        run: yarn version prerelease

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          currentVersion=$(jq -r .version package.json)
          targetVersion="$currentVersion-pre.$calculatedSha"
          echo "target_version=$targetVersion" >> $GITHUB_OUTPUT

      - name: Bump versions
        run: yarn workspaces foreach --all version ${{ steps.vars.outputs.target_version }}

      - name: Publish packages
        run: yarn deploy --filter="./packages/*" --cache-dir ./turbo -- --tag pre
        env:
          GITHUB_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
